spring:
  profiles:
    active:
      -dev
---
server:
  port: 8778
spring:
  profiles: dev #开发环境
  application:
    name: micro-city-detail-introduce
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8778
spring:
  profiles: test
  application:
    name: micro-city-detail-introduce
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/