spring:
  profiles:
    active:
      -dev
---
server:
  port: 8201
spring:
  profiles: dev #开发环境
  application:
    name: micro-weather-config-client
eureka:
  client:
    service-url:
	  defaultZone: http://localhost:8761/eureka/
	  
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: micro-weather-config-client
eureka:
  client:
    service-url:
	  defaultZone: http://localhost:8761/eureka/